import pygame 

# Grid
BOARD_HEIGHT = 50
BOARD_WIDTH = 50
SCREEN_HEIGHT = 400
SCREEN_WIDTH = 40
HEIGHT=SCREEN_HEIGHT/BOARD_HEIGHT
WIDTH=SCREEN_WIDTH/BOARD_WIDTH

SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

# Colours
BLUE=(0,0,255)
BLACK=(27,27,27)